INSERT INTO esibizioni (id, nazione, cantante, titolo) VALUES
(1, 'Norvegia', 'Kyle Alessandro', 'Lighter'),
(2, 'Lussemburgo', 'Laura Thorn', 'La Poupée Monte Le Son'),
(3, 'Estonia', 'Tommy Cash', 'Espresso Macchiato'),
(4, 'Israele', 'Yuval Raphael', 'New Day Will Rise'),
(5, 'Lituania', 'Katarsis', 'Tavo Akys'),
(6, 'Spagna', 'Melody', 'ESA DIVA'),
(7, 'Ucraina', 'Ziferblat', 'Bird of Pray'),
(8, 'Regno Unito', 'Remember Monday', 'What The Hell Just Happened?'),
(9, 'Austria', 'JJ', 'Wasted Love'),
(10, 'Islanda', 'VÆB', 'RÓA'),
(11, 'Lettonia', 'Tautumeitas', 'Bur Man Laimi'),
(12, 'Paesi Bassi', 'Claude', 'C’est La Vie'),
(13, 'Finlandia', 'Erika Vikman', 'ICH KOMME'),
(14, 'Italia', 'Lucio Corsi', 'Volevo Essere Un Duro'),
(15, 'Polonia', 'Justyna Steczkowska', 'GAJA'),
(16, 'Germania', 'Abor & Tynna', 'Baller'),
(17, 'Grecia', 'Klavdia', 'Asteromáta'),
(18, 'Armenia', 'PARG', 'SURVIVOR'),
(19, 'Svizzera', 'Zoë Më', 'Voyage'),
(20, 'Malta', 'Miriana Conte', 'SERVING'),
(21, 'Portogallo', 'NAPA', 'Deslocado'),
(22, 'Danimarca', 'Sissal', 'Hallucination'),
(23, 'Svezia', 'KAJ', 'Bara Bada Bastu'),
(24, 'Francia', 'Louane', 'maman'),
(25, 'San Marino', 'Gabry Ponte', 'Tutta L’Italia'),
(26, 'Albania', 'Shkodra Elektronike', 'Zjerm');
